spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/data_store
    username: root
    password: Mysql@1234
    driver-class-name: com.mysql.cj.jdbc.Driver